spring:
  datasource:
      url: jdbc:mysql://localhost:3306/users?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root@123
  #JPA Settings
  jpa.hibernate.ddl_auto: update
  jpa.show-sql: true

server:
  port: 8087